### ISSUE TITLE
Kanban board review

### ISSUE THREAD

**Issue by daudi13** [daudi13/Recipe-app#10]
Hello,

Our team is made up of two members @daudi13  and @Abenezer-Tilahun.
This is the link to our [project](https://github.com/daudi13/Recipe-app/projects/2)

---
Thank you for taking the time to review our project.

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @daudi13 and @Abenezer-Tilahun,

Good job so far!
✔️ Tasks are properly assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Your board is missing the **`In review`** column. Kindly add it.

- [ ] I can't find any tasks that cater to these. Kindly add them.

  ![ouma-n+1](https://user-images.githubusercontent.com/36542986/175925246-e9d51149-7cdc-427f-b14f-72fde4606fe8.jpg)

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by daudi13** [comment]
thank you for pointing that out @TedLivist . I've fixed the two issues

**Comment by julie-ify** [comment]
Hi @daudi13 and @Abenezer-Tilahun, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by daudi13** [comment]
thank you @julie-ify
